import Head from "next/head";
import { Body } from "./layout/Typography";
import { PageLayout } from "./layout/Page";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PageLayout>
          <Body>Howdy</Body>
        </PageLayout>
      </main>

      <footer></footer>
    </div>
  );
}
