import Head from "next/head";
import { Body, HeaderTitle, Headline, LargeTitle } from "./layout/Typography";
import { PageLayout } from "./layout/Page";
import css, { styled } from "styled-components";
import { Flex } from "./layout/Flex";
import {
  ADMINISTRATE_LINK,
  ARDUINO_PROPOSAL_LINK,
  CAREER_CHANGE_LINK,
  FANDUEL_LINK,
  VAULT_BILLBOARD_LINK,
} from "../constants";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Simon's personal site, generated by create next app" />
      </Head>

      <main>
        <PageLayout>
          <Flex align={"flex-start"} gap={"var(--spacing-md)"}>
            <Flex align={"flex-start"} direction={"column"} flex={1}>
              <HeaderTitle>Simon Atkins</HeaderTitle>
              <Headline>Front-End Engineer</Headline>
              <StyledBody>I build high-quality digital experiences for the web</StyledBody>
            </Flex>
            <Flex direction={"column"} flex={1} gap={"var(--spacing-lg)"}>
              <Body>
                Back in 2016, I decided to propose to my girlfriend by coding a
                treasure-hunt-marriage-proposal box out of an{" "}
                <a href={ARDUINO_PROPOSAL_LINK}>antique toolbox and an Arduino microprocessor</a>.
                (She said yes.)
              </Body>
              <Body>
                I was hooked on coding, and shortly after I left my comfortable marketing job for an{" "}
                <a href={CAREER_CHANGE_LINK}>exciting new career</a> in software development. Soon I
                would be working as a full-stack developer at{" "}
                <a href={ADMINISTRATE_LINK}>Administrate</a> before moving to a new startup,{" "}
                <a href={VAULT_BILLBOARD_LINK}>VAULT</a>, led by the founders of{" "}
                <a href={FANDUEL_LINK}>FanDuel</a>.
              </Body>
              <Body>
                I naturally gravitated towards front-end development, specialising in frameworks
                such as React and NextJS, and my main focus these days is delivering responsive and
                beautiful web apps and internal tools.
              </Body>
              <Body>
                When I'm not at a computer I can usually be found raising an energetic toddler,
                taking on overly-ambitious DIY projects, and rearing chickens.
              </Body>
              <ExperienceContainer direction={"column"}>
                <ul
                  css={`
                    width: 100%;
                  `}
                >
                  <ExperienceItem>
                    <Flex align={"flex-start"} justify={"space-between"} gap={"var(--spacing-md)"}>
                      <Flex
                        css={`
                          text-transform: uppercase;
                        `}
                        flex={1}
                      >
                        2001 - Present
                      </Flex>
                      <Flex flex={3} justify={"flex-start"}>
                        <Flex direction={"column"} align={"baseline"}>
                          <Body>Did some coding</Body>
                          <Body> And some other things</Body>
                        </Flex>
                      </Flex>
                    </Flex>
                  </ExperienceItem>
                </ul>
              </ExperienceContainer>
            </Flex>
          </Flex>
        </PageLayout>
      </main>

      <footer></footer>
    </div>
  );
}

const StyledBody = styled(Body)`
  padding-top: var(--spacing-md);
`;

const ExperienceContainer = styled(Flex)`
  align-items: flex-start;
  width: 100%;
`;

const ExperienceItem = styled.li``;
