import Head from "next/head";
import { Body, Headline, LargeTitle } from "./layout/Typography";
import { PageLayout } from "./layout/Page";
import css, { styled } from "styled-components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PageLayout>
          <LargeTitle>Hi, I'm Simon Atkins</LargeTitle>
          <Headline>Front-End Engineer</Headline>
          <Body>I build digital experiences for the web</Body>
        </PageLayout>
      </main>

      <footer></footer>
    </div>
  );
}

// const StyledBody = styled(Body)`
//   padding-top: var(--spacing-md);
// `;
